const mongoose = require('mongoose');

const columnSchema = new mongoose.Schema(
    {
        name: {
            type: String,
            required: true,
            trim: true,
        },

        detectedType: {
            type: String,
            enum: ['number', 'string', 'boolean', 'date', 'mixed', 'empty'],
            required: true,
        },

        totalValues: {
            type: Number,
            default: 0,
            min: 0,
        },

        missingValues: {
            type: Number,
            default: 0,
            min: 0,
        },

        uniqueValues: {
            type: Number,
            default: 0,
            min: 0,
        },

        sampleValues: {
            type: [mongoose.Schema.Types.Mixed],
            default: [],
        },
    },
    { _id: false }
);

const numericStatsSchema = new mongoose.Schema(
    {
        columnName: {
            type: String,
            required: true,
            trim: true,
        },

        min: Number,
        max: Number,
        average: Number,
        median: Number,
        mode: mongoose.Schema.Types.Mixed,
        standardDeviation: Number,

        outliers: {
            count: {
                type: Number,
                default: 0,
                min: 0,
            },
            sampleValues: {
                type: [Number],
                default: [],
            },
            method: {
                type: String,
                default: 'iqr',
            },
        },
    },
    { _id: false }
);

const categoryFrequencySchema = new mongoose.Schema(
    {
        columnName: {
            type: String,
            required: true,
            trim: true,
        },

        values: [
            {
                label: {
                    type: String,
                    required: true,
                },
                count: {
                    type: Number,
                    required: true,
                    min: 0,
                },
                percentage: {
                    type: Number,
                    min: 0,
                    max: 100,
                },
            },
        ],
    },
    { _id: false }
);

const chartSchema = new mongoose.Schema(
    {
        chartId: {
            type: String,
            required: true,
        },

        title: {
            type: String,
            required: true,
            trim: true,
        },

        chartType: {
            type: String,
            enum: ['bar', 'pie', 'line', 'histogram', 'table'],
            required: true,
        },

        xAxis: {
            type: String,
            default: '',
        },

        yAxis: {
            type: String,
            default: '',
        },

        data: {
            type: [mongoose.Schema.Types.Mixed],
            default: [],
        },

        isAutoGenerated: {
            type: Boolean,
            default: true,
        },
    },
    { _id: false }
);

const tablePreviewSchema = new mongoose.Schema(
    {
        columns: {
            type: [String],
            default: [],
        },

        rows: {
            type: [[mongoose.Schema.Types.Mixed]],
            default: [],
        },

        maxRowsShown: {
            type: Number,
            default: 20,
        },
    },
    { _id: false }
);

const analysisReportSchema = new mongoose.Schema(
    {
        title: {
            type: String,
            required: [true, 'Report title is required'],
            trim: true,
            minlength: [2, 'Report title must be at least 2 characters long'],
            maxlength: [120, 'Report title cannot exceed 120 characters'],
        },

        originalFileName: {
            type: String,
            required: true,
            trim: true,
        },

        storedFilePath: {
            type: String,
            required: true,
        },

        fileType: {
            type: String,
            enum: ['csv', 'json', 'xlsx'],
            required: true,
        },

        mimeType: {
            type: String,
            default: '',
        },

        fileSize: {
            type: Number,
            required: true,
            min: 0,
        },

        fileRetentionExpiresAt: {
            type: Date,
            required: true,
        },

        isOriginalFileAvailable: {
            type: Boolean,
            default: true,
        },

        rowCount: {
            type: Number,
            required: true,
            min: 0,
        },

        columnCount: {
            type: Number,
            required: true,
            min: 0,
        },

        columns: {
            type: [columnSchema],
            default: [],
        },

        summaryStatistics: {
            numeric: {
                type: [numericStatsSchema],
                default: [],
            },

            categorical: {
                type: [categoryFrequencySchema],
                default: [],
            },
        },

        missingValues: {
            totalMissingValues: {
                type: Number,
                default: 0,
                min: 0,
            },

            byColumn: [
                {
                    columnName: {
                        type: String,
                        required: true,
                    },
                    missingValues: {
                        type: Number,
                        required: true,
                        min: 0,
                    },
                    percentage: {
                        type: Number,
                        min: 0,
                        max: 100,
                    },
                },
            ],
        },

        duplicateRowCount: {
            type: Number,
            default: 0,
            min: 0,
        },

        outlierSummary: {
            totalOutliers: {
                type: Number,
                default: 0,
                min: 0,
            },

            columnsWithOutliers: {
                type: [String],
                default: [],
            },
        },

        textualInsights: {
            type: [String],
            default: [],
        },

        chartData: {
            type: [chartSchema],
            default: [],
        },

        tablePreview: {
            type: tablePreviewSchema,
            default: () => ({}),
        },

        tags: {
            type: [String],
            default: [],
        },

        descriptionCategory: {
            type: String,
            enum: [
                'sales',
                'finance',
                'education',
                'operations',
                'research',
                'marketing',
                'personal',
                'other',
                '',
            ],
            default: '',
        },

        owner: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
            index: true,
        },

        isDeleted: {
            type: Boolean,
            default: false,
            index: true,
        },

        deletedAt: {
            type: Date,
            default: null,
        },
    },
    {
        timestamps: true,
    }
);

analysisReportSchema.index({ owner: 1, createdAt: -1 });
analysisReportSchema.index({ owner: 1, isDeleted: 1 });
analysisReportSchema.index({ title: 'text', originalFileName: 'text', tags: 'text' });

module.exports = mongoose.model('AnalysisReport', analysisReportSchema);