const buildBarChartFromCategory = (categoryStat) => {
  return {
    chartId: `bar-${categoryStat.columnName}`,
    title: `${categoryStat.columnName} frequency`,
    chartType: 'bar',
    xAxis: categoryStat.columnName,
    yAxis: 'Count',
    data: categoryStat.values.map((item) => ({
      label: item.label,
      value: item.count,
      percentage: item.percentage,
    })),
    isAutoGenerated: true,
  };
};

const buildPieChartFromCategory = (categoryStat) => {
  return {
    chartId: `pie-${categoryStat.columnName}`,
    title: `${categoryStat.columnName} distribution`,
    chartType: 'pie',
    xAxis: categoryStat.columnName,
    yAxis: 'Percentage',
    data: categoryStat.values.map((item) => ({
      label: item.label,
      value: item.count,
      percentage: item.percentage,
    })),
    isAutoGenerated: true,
  };
};

const buildHistogramFromNumeric = (numericStat) => {
  const min = numericStat.min;
  const max = numericStat.max;
  const values = numericStat.values || [];

  if (min === null || max === null || min === max || values.length === 0) {
    return null;
  }

  const bucketCount = 8;
  const bucketSize = (max - min) / bucketCount;

  const buckets = Array.from({ length: bucketCount }, (_, index) => {
    const start = min + index * bucketSize;
    const end = index === bucketCount - 1 ? max : start + bucketSize;

    return {
      label: `${Number(start.toFixed(2))} - ${Number(end.toFixed(2))}`,
      min: start,
      max: end,
      value: 0,
    };
  });

  values.forEach((value) => {
    const bucketIndex =
      value === max
        ? bucketCount - 1
        : Math.floor((value - min) / bucketSize);

    if (buckets[bucketIndex]) {
      buckets[bucketIndex].value += 1;
    }
  });

  return {
    chartId: `histogram-${numericStat.columnName}`,
    title: `${numericStat.columnName} distribution`,
    chartType: 'histogram',
    xAxis: numericStat.columnName,
    yAxis: 'Frequency',
    data: buckets,
    isAutoGenerated: true,
  };
};

const parseChartNumber = (value) => {
  if (value === null || value === undefined) return null;

  const normalized = String(value).trim();

  if (normalized === '') return null;

  const number = Number(normalized.replace(/,/g, ''));

  return Number.isFinite(number) ? number : null;
};

const buildLineChartFromNumeric = (rows, numericStat) => {
  const columnName = numericStat.columnName;

  const data = rows
    .slice(0, 50)
    .map((row, index) => {
      const value = parseChartNumber(row[columnName]);

      if (value === null) return null;

      return {
        label: index + 1,
        value,
      };
    })
    .filter(Boolean);

  if (data.length < 2) return null;

  return {
    chartId: `line-${columnName}`,
    title: `${columnName} trend by row order`,
    chartType: 'line',
    xAxis: 'Row',
    yAxis: columnName,
    data,
    isAutoGenerated: true,
  };
};

const buildAutoCharts = (rows, analysis) => {
  const charts = [];

  const categoricalStats = analysis.summaryStatistics.categorical || [];
  const numericStats = analysis.summaryStatistics.numeric || [];

  categoricalStats.slice(0, 2).forEach((categoryStat) => {
    if (categoryStat.values.length > 0) {
      charts.push(buildBarChartFromCategory(categoryStat));

      if (categoryStat.values.length <= 8) {
        charts.push(buildPieChartFromCategory(categoryStat));
      }
    }
  });

  numericStats.slice(0, 2).forEach((numericStat) => {
    const histogram = buildHistogramFromNumeric(numericStat);
    const lineChart = buildLineChartFromNumeric(rows, numericStat);

    if (histogram) charts.push(histogram);
    if (lineChart) charts.push(lineChart);
  });

  charts.push({
    chartId: 'table-preview',
    title: 'Table preview',
    chartType: 'table',
    xAxis: '',
    yAxis: '',
    data: analysis.tablePreview.rows,
    isAutoGenerated: true,
  });

  return charts;
};

module.exports = {
  buildAutoCharts,
};