import {
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Legend,
  Line,
  LineChart,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts';

const chartColors = [
  '#38bdf8',
  '#818cf8',
  '#34d399',
  '#fbbf24',
  '#fb7185',
  '#a78bfa',
  '#22d3ee',
  '#f97316',
];

function normalizeChartData(chart) {
  if (!Array.isArray(chart?.data)) {
    return [];
  }

  if (chart.chartType === 'table') {
    return [];
  }

  return chart.data
    .map((item, index) => ({
      name: String(item.label ?? `Item ${index + 1}`),
      value: Number(item.value ?? 0),
      percentage: Number(item.percentage ?? 0),
      min: item.min,
      max: item.max,
    }))
    .filter((item) => Number.isFinite(item.value));
}

function ChartTooltip({ active, payload, label }) {
  if (!active || !payload?.length) {
    return null;
  }

  const item = payload[0]?.payload;

  return (
    <div className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-sm shadow-xl">
      <p className="font-semibold text-white">{label || item?.name}</p>
      <p className="mt-1 text-sky-300">Value: {payload[0].value}</p>
      {Number.isFinite(item?.percentage) && item.percentage > 0 && (
        <p className="text-slate-400">
          Percentage: {item.percentage.toFixed(2)}%
        </p>
      )}
    </div>
  );
}

function ChartPanel({ chart }) {
  const data = normalizeChartData(chart);

  if (!chart || chart.chartType === 'table') {
    return null;
  }

  if (!data.length) {
    return (
      <section className="rounded-3xl border border-slate-800 bg-slate-950/80 p-6">
        <h3 className="text-lg font-semibold text-white">
          {chart.title || 'Chart'}
        </h3>
        <p className="mt-2 text-sm text-slate-400">
          This chart does not contain renderable numeric data.
        </p>
      </section>
    );
  }

  return (
    <section className="rounded-3xl border border-slate-800 bg-slate-950/80 p-6">
      <div className="mb-5 flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="text-xs font-semibold uppercase tracking-[0.2em] text-sky-300">
            {chart.chartType}
          </p>
          <h3 className="mt-2 text-lg font-semibold text-white">
            {chart.title || 'Untitled chart'}
          </h3>
        </div>

        {chart.isAutoGenerated && (
          <span className="rounded-full border border-slate-700 px-3 py-1 text-xs text-slate-300">
            Auto generated
          </span>
        )}
      </div>

      <div className="h-80">
        <ResponsiveContainer width="100%" height="100%">
          {chart.chartType === 'bar' || chart.chartType === 'histogram' ? (
            <BarChart data={data}>
              <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
              <XAxis
                dataKey="name"
                stroke="#94a3b8"
                tick={{ fontSize: 12 }}
                interval={0}
                angle={data.length > 5 ? -20 : 0}
                textAnchor={data.length > 5 ? 'end' : 'middle'}
                height={data.length > 5 ? 70 : 40}
              />
              <YAxis stroke="#94a3b8" tick={{ fontSize: 12 }} />
              <Tooltip content={<ChartTooltip />} />
              <Bar dataKey="value" radius={[8, 8, 0, 0]} fill="#38bdf8" />
            </BarChart>
          ) : chart.chartType === 'line' ? (
            <LineChart data={data}>
              <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
              <XAxis dataKey="name" stroke="#94a3b8" tick={{ fontSize: 12 }} />
              <YAxis stroke="#94a3b8" tick={{ fontSize: 12 }} />
              <Tooltip content={<ChartTooltip />} />
              <Line
                type="monotone"
                dataKey="value"
                stroke="#38bdf8"
                strokeWidth={3}
                dot={{ r: 4, fill: '#38bdf8' }}
                activeDot={{ r: 6 }}
              />
            </LineChart>
          ) : chart.chartType === 'pie' ? (
            <PieChart>
              <Tooltip content={<ChartTooltip />} />
              <Legend />
              <Pie
                data={data}
                dataKey="value"
                nameKey="name"
                outerRadius={105}
                innerRadius={45}
                paddingAngle={3}
              >
                {data.map((entry, index) => (
                  <Cell
                    key={entry.name}
                    fill={chartColors[index % chartColors.length]}
                  />
                ))}
              </Pie>
            </PieChart>
          ) : (
            <BarChart data={data}>
              <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
              <XAxis dataKey="name" stroke="#94a3b8" tick={{ fontSize: 12 }} />
              <YAxis stroke="#94a3b8" tick={{ fontSize: 12 }} />
              <Tooltip content={<ChartTooltip />} />
              <Bar dataKey="value" radius={[8, 8, 0, 0]} fill="#38bdf8" />
            </BarChart>
          )}
        </ResponsiveContainer>
      </div>
    </section>
  );
}

export default ChartPanel;