import {
  Area,
  AreaChart,
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Label,
  Legend,
  Line,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts';

import { usePreferences } from '../../context/PreferencesContext.jsx';
import StatusBadge from '../common/StatusBadge.jsx';

const chartColors = [
  '#38bdf8',
  '#22d3ee',
  '#818cf8',
  '#34d399',
  '#fbbf24',
  '#a78bfa',
  '#fb7185',
  '#f97316',
];

function formatNumber(value) {
  const number = Number(value);

  if (!Number.isFinite(number)) {
    return '0';
  }

  return new Intl.NumberFormat('en', {
    notation: Math.abs(number) >= 10000 ? 'compact' : 'standard',
    maximumFractionDigits: 2,
  }).format(number);
}

function normalizeChartData(chart) {
  if (!Array.isArray(chart?.data) || chart.chartType === 'table') {
    return [];
  }

  return chart.data
    .map((item, index) => ({
      name: String(item.label ?? `Item ${index + 1}`),
      value: Number(item.value ?? 0),
      percentage: Number(item.percentage ?? 0),
      min: Number(item.min),
      max: Number(item.max),
    }))
    .filter((item) => Number.isFinite(item.value));
}

function truncateLabel(value, maxLength = 18) {
  const text = String(value ?? '');

  return text.length > maxLength
    ? `${text.slice(0, maxLength - 1)}…`
    : text;
}

function ChartTooltip({ active, payload, label }) {
  if (!active || !payload?.length) {
    return null;
  }

  const item = payload[0]?.payload;
  const value = payload[0]?.value;

  return (
    <div className="min-w-40 rounded-2xl border border-slate-700/80 bg-slate-950/95 px-4 py-3 shadow-2xl shadow-black/40 backdrop-blur">
      <p className="max-w-56 break-words text-sm font-semibold text-white">
        {label || item?.name}
      </p>

      <div className="mt-2 flex items-center justify-between gap-5">
        <span className="text-xs text-slate-400">
          Value
        </span>

        <span className="text-sm font-semibold text-sky-300">
          {formatNumber(value)}
        </span>
      </div>

      {Number.isFinite(item?.percentage) &&
        item.percentage > 0 && (
          <div className="mt-1 flex items-center justify-between gap-5">
            <span className="text-xs text-slate-400">
              Share
            </span>

            <span className="text-sm font-medium text-slate-200">
              {item.percentage.toFixed(1)}%
            </span>
          </div>
        )}
    </div>
  );
}

function ChartPanel({
  chart,
  featured = false,
  compact = false,
}) {
  const { preferences } = usePreferences();

  const data = normalizeChartData(chart);
  const chartAnimationsEnabled =
    preferences.interfaceMotion;

  if (!chart || chart.chartType === 'table') {
    return null;
  }

  if (!data.length) {
    return (
      <section className="rounded-3xl border border-slate-800/80 bg-slate-950/70 p-6 shadow-xl shadow-slate-950/20">
        <StatusBadge variant="warning">
          No chart data
        </StatusBadge>

        <h3 className="mt-4 text-lg font-semibold text-white">
          {chart.title || 'Chart'}
        </h3>

        <p className="mt-2 text-sm leading-6 text-slate-400">
          This chart does not contain renderable numeric values.
        </p>
      </section>
    );
  }

  const total = data.reduce(
    (sum, item) => sum + item.value,
    0
  );

  const longLabels = data.some(
    (item) => item.name.length > 14
  );

  const chartHeight = compact
    ? 'h-64'
    : featured
      ? 'h-[26rem]'
      : 'h-80';

  const chartType = chart.chartType?.toLowerCase();
  const isBar =
    chartType === 'bar' || chartType === 'histogram';
  const isLine = chartType === 'line';
  const isPie = chartType === 'pie';

  return (
    <section
      className={`relative min-w-0 overflow-hidden rounded-3xl border border-slate-800/80 bg-slate-950/70 shadow-xl shadow-slate-950/20 backdrop-blur transition hover:border-slate-700 ${featured ? 'p-6 sm:p-7' : 'p-5 sm:p-6'
        }`}
    >
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(14,165,233,0.08),transparent_22rem)]" />

      <div className="relative">
        <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div className="min-w-0">
            <div className="flex flex-wrap items-center gap-2">
              <StatusBadge variant="info">
                {chartType || 'chart'}
              </StatusBadge>

              {featured && (
                <StatusBadge variant="success" showDot>
                  Featured
                </StatusBadge>
              )}

              {chart.isAutoGenerated && (
                <StatusBadge variant="neutral">
                  Auto generated
                </StatusBadge>
              )}
            </div>

            <h3 className="mt-4 break-words text-lg font-semibold tracking-tight text-white sm:text-xl">
              {chart.title || 'Untitled chart'}
            </h3>

            <p className="mt-2 text-sm leading-6 text-slate-400">
              {data.length} data point
              {data.length === 1 ? '' : 's'} visualized
              {Number.isFinite(total)
                ? ` · Total ${formatNumber(total)}`
                : ''}
            </p>
          </div>
        </div>

        <div className={`${chartHeight} min-w-0`}>
          <ResponsiveContainer width="100%" height="100%">
            {isBar ? (
              longLabels && data.length <= 12 ? (
                <BarChart
                  data={data}
                  layout="vertical"
                  margin={{
                    top: 10,
                    right: 18,
                    bottom: 10,
                    left: 26,
                  }}
                >
                  <defs>
                    <linearGradient
                      id="barGradientHorizontal"
                      x1="0"
                      y1="0"
                      x2="1"
                      y2="0"
                    >
                      <stop
                        offset="0%"
                        stopColor="#0ea5e9"
                      />
                      <stop
                        offset="100%"
                        stopColor="#22d3ee"
                      />
                    </linearGradient>
                  </defs>

                  <CartesianGrid
                    stroke="#1e293b"
                    strokeDasharray="4 6"
                    horizontal={false}
                  />

                  <XAxis
                    type="number"
                    stroke="#64748b"
                    tick={{
                      fontSize: 11,
                      fill: '#94a3b8',
                    }}
                    tickFormatter={formatNumber}
                    axisLine={false}
                    tickLine={false}
                  />

                  <YAxis
                    type="category"
                    dataKey="name"
                    width={110}
                    stroke="#64748b"
                    tick={{
                      fontSize: 11,
                      fill: '#cbd5e1',
                    }}
                    tickFormatter={(value) =>
                      truncateLabel(value, 16)
                    }
                    axisLine={false}
                    tickLine={false}
                  />

                  <Tooltip
                    content={<ChartTooltip />}
                    cursor={{ fill: '#0f172a' }}
                  />

                  <Bar
                    dataKey="value"
                    fill="url(#barGradientHorizontal)"
                    radius={[0, 8, 8, 0]}
                    maxBarSize={28}
                    isAnimationActive={
                      chartAnimationsEnabled
                    }
                  />
                </BarChart>
              ) : (
                <BarChart
                  data={data}
                  margin={{
                    top: 10,
                    right: 12,
                    bottom: longLabels ? 34 : 10,
                    left: 0,
                  }}
                >
                  <defs>
                    <linearGradient
                      id="barGradientVertical"
                      x1="0"
                      y1="1"
                      x2="0"
                      y2="0"
                    >
                      <stop
                        offset="0%"
                        stopColor="#0284c7"
                      />
                      <stop
                        offset="100%"
                        stopColor="#38bdf8"
                      />
                    </linearGradient>
                  </defs>

                  <CartesianGrid
                    stroke="#1e293b"
                    strokeDasharray="4 6"
                    vertical={false}
                  />

                  <XAxis
                    dataKey="name"
                    stroke="#64748b"
                    tick={{
                      fontSize: 11,
                      fill: '#94a3b8',
                    }}
                    tickFormatter={(value) =>
                      truncateLabel(value, 12)
                    }
                    angle={longLabels ? -25 : 0}
                    textAnchor={
                      longLabels ? 'end' : 'middle'
                    }
                    axisLine={false}
                    tickLine={false}
                  />

                  <YAxis
                    stroke="#64748b"
                    tick={{
                      fontSize: 11,
                      fill: '#94a3b8',
                    }}
                    tickFormatter={formatNumber}
                    axisLine={false}
                    tickLine={false}
                  />

                  <Tooltip
                    content={<ChartTooltip />}
                    cursor={{ fill: '#0f172a' }}
                  />

                  <Bar
                    dataKey="value"
                    fill="url(#barGradientVertical)"
                    radius={[8, 8, 2, 2]}
                    maxBarSize={46}
                    isAnimationActive={
                      chartAnimationsEnabled
                    }
                  />
                </BarChart>
              )
            ) : isLine ? (
              <AreaChart
                data={data}
                margin={{
                  top: 12,
                  right: 18,
                  bottom: 12,
                  left: 0,
                }}
              >
                <defs>
                  <linearGradient
                    id="lineAreaGradient"
                    x1="0"
                    y1="0"
                    x2="0"
                    y2="1"
                  >
                    <stop
                      offset="0%"
                      stopColor="#38bdf8"
                      stopOpacity={0.34}
                    />
                    <stop
                      offset="100%"
                      stopColor="#38bdf8"
                      stopOpacity={0.02}
                    />
                  </linearGradient>
                </defs>

                <CartesianGrid
                  stroke="#1e293b"
                  strokeDasharray="4 6"
                  vertical={false}
                />

                <XAxis
                  dataKey="name"
                  stroke="#64748b"
                  tick={{
                    fontSize: 11,
                    fill: '#94a3b8',
                  }}
                  tickFormatter={(value) =>
                    truncateLabel(value, 12)
                  }
                  axisLine={false}
                  tickLine={false}
                />

                <YAxis
                  stroke="#64748b"
                  tick={{
                    fontSize: 11,
                    fill: '#94a3b8',
                  }}
                  tickFormatter={formatNumber}
                  axisLine={false}
                  tickLine={false}
                />

                <Tooltip content={<ChartTooltip />} />

                <Area
                  type="monotone"
                  dataKey="value"
                  stroke="none"
                  fill="url(#lineAreaGradient)"
                  isAnimationActive={
                    chartAnimationsEnabled
                  }
                />

                <Line
                  type="monotone"
                  dataKey="value"
                  stroke="#38bdf8"
                  strokeWidth={3}
                  dot={{
                    r: 3,
                    fill: '#38bdf8',
                    strokeWidth: 0,
                  }}
                  activeDot={{
                    r: 6,
                    fill: '#e0f2fe',
                    stroke: '#38bdf8',
                    strokeWidth: 3,
                  }}
                  isAnimationActive={
                    chartAnimationsEnabled
                  }
                />
              </AreaChart>
            ) : isPie ? (
              <PieChart>
                <Tooltip content={<ChartTooltip />} />

                <Legend
                  verticalAlign="bottom"
                  iconType="circle"
                  formatter={(value) => (
                    <span className="text-xs text-slate-300">
                      {truncateLabel(value, 18)}
                    </span>
                  )}
                />

                <Pie
                  data={data}
                  dataKey="value"
                  nameKey="name"
                  innerRadius="52%"
                  outerRadius="76%"
                  paddingAngle={0}
                  stroke="none"
                  isAnimationActive={
                    chartAnimationsEnabled
                  }
                >
                  {data.map((entry, index) => (
                    <Cell
                      key={`${entry.name}-${index}`}
                      fill={
                        chartColors[
                        index % chartColors.length
                        ]
                      }
                    />
                  ))}

                  <Label
                    position="center"
                    content={({ viewBox }) => {
                      const { cx, cy } = viewBox || {};

                      return (
                        <g>
                          <text
                            x={cx}
                            y={cy - 6}
                            textAnchor="middle"
                            fill="#ffffff"
                            fontSize="22"
                            fontWeight="700"
                          >
                            {formatNumber(total)}
                          </text>

                          <text
                            x={cx}
                            y={cy + 16}
                            textAnchor="middle"
                            fill="#94a3b8"
                            fontSize="11"
                          >
                            total
                          </text>
                        </g>
                      );
                    }}
                  />
                </Pie>
              </PieChart>
            ) : (
              <BarChart data={data}>
                <CartesianGrid
                  stroke="#1e293b"
                  strokeDasharray="4 6"
                  vertical={false}
                />

                <XAxis
                  dataKey="name"
                  stroke="#64748b"
                  tick={{
                    fontSize: 11,
                    fill: '#94a3b8',
                  }}
                  tickFormatter={(value) =>
                    truncateLabel(value, 12)
                  }
                  axisLine={false}
                  tickLine={false}
                />

                <YAxis
                  stroke="#64748b"
                  tick={{
                    fontSize: 11,
                    fill: '#94a3b8',
                  }}
                  tickFormatter={formatNumber}
                  axisLine={false}
                  tickLine={false}
                />

                <Tooltip content={<ChartTooltip />} />

                <Bar
                  dataKey="value"
                  radius={[8, 8, 2, 2]}
                  fill="#38bdf8"
                  maxBarSize={46}
                  isAnimationActive={
                    chartAnimationsEnabled
                  }
                />
              </BarChart>
            )}
          </ResponsiveContainer>
        </div>
      </div>
    </section>
  );
}

export default ChartPanel;